In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
#Importing necessary libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import cv2
import tensorflow as tf
from PIL import Image
import os
from sklearn.model_selection import train_test_split
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout
from keras.models import Sequential

In [ ]:
data = []
labels = []
classes = 4
cur_path = '/content/gdrive/MyDrive/Sunik_sample_data/data'

In [ ]:
cur_path

'/content/gdrive/MyDrive/Sunik_sample_data/data'

In [ ]:
for i in range(classes):
    path = os.path.join(cur_path,'train',str(i))
    print(path)

/content/gdrive/MyDrive/Sunik_sample_data/data/train/0
/content/gdrive/MyDrive/Sunik_sample_data/data/train/1
/content/gdrive/MyDrive/Sunik_sample_data/data/train/2
/content/gdrive/MyDrive/Sunik_sample_data/data/train/3


In [ ]:
#Retrieving the images and their labels 
for i in range(classes):
    path = os.path.join(cur_path,'train',str(i))
    images = os.listdir(path)
    print(images)
    

['typhoon.png', 'typhoon02.png', 'Screenshot 2021-12-22 at 6.22.04 PM.png', 'Screenshot 2021-12-22 at 6.22.14 PM.png', 'Screenshot 2021-12-22 at 6.22.41 PM.png', 'Screenshot 2021-12-22 at 6.23.08 PM.png', 'typhon03.png', 'Screenshot 2021-12-22 at 6.23.43 PM.png', 'Screenshot 2021-12-22 at 6.23.56 PM.png', 'Screenshot 2021-12-22 at 6.24.21 PM.png', 'Screenshot 2021-12-22 at 6.25.00 PM.png', 'Screenshot 2021-12-22 at 6.25.16 PM.png', 'Screenshot 2021-12-22 at 6.25.38 PM.png', 'Screenshot 2021-12-22 at 6.26.05 PM.png', 'Screenshot 2021-12-22 at 7.59.44 PM.png', 'Screenshot 2021-12-22 at 8.13.29 PM.png', 'Screenshot 2021-12-22 at 8.13.47 PM.png', 'Screenshot 2021-12-22 at 8.14.05 PM.png', 'Screenshot 2021-12-22 at 8.14.28 PM.png', 'Screenshot 2021-12-22 at 8.14.47 PM.png', 'Screenshot 2021-12-22 at 8.15.03 PM.png', 'Screenshot 2021-12-22 at 8.15.23 PM.png', 'Screenshot 2021-12-22 at 8.31.33 PM.png', 'Screenshot 2021-12-22 at 8.32.11 PM.png', 'Screenshot 2021-12-22 at 8.32.26 PM.png', 'Scre

In [ ]:
for a in images:
        try:
           image = Image.open(path +'//'+ a)
#print(image)
           image = image.resize((100,100))
#print(image)            
           image = np.array(image)
#print(image)           
           #sim = Image.fromarray(image)
           data.append(image)
#print(image)            
           labels.append(i)
#print(image)           
        except:
            print("Error loading image")


In [ ]:
data = np.array(data)
labels = np.array(labels)

In [ ]:
print(data)
#pixcel

[[[[ 53  59  75 255]
   [ 29  35  51 255]
   [ 17  23  39 255]
   ...
   [ 70  75  83 255]
   [ 74  79  84 255]
   [ 79  84  88 255]]

  [[ 47  53  69 255]
   [ 48  54  70 255]
   [ 26  32  48 255]
   ...
   [ 71  75  83 255]
   [ 67  72  78 255]
   [107 112 116 255]]

  [[ 35  41  57 255]
   [ 54  60  77 255]
   [ 33  39  55 255]
   ...
   [ 50  55  63 255]
   [ 83  88  94 255]
   [139 144 148 255]]

  ...

  [[  3   5  21 255]
   [  3   5  20 255]
   [  3   5  20 255]
   ...
   [ 92  97 112 255]
   [141 144 153 255]
   [180 184 185 255]]

  [[  3   5  20 255]
   [  3   5  20 255]
   [  3   5  20 255]
   ...
   [ 64  69  86 255]
   [136 141 147 255]
   [174 179 175 255]]

  [[  3   5  20 255]
   [  3   5  20 255]
   [  3   5  20 255]
   ...
   [ 72  77  96 255]
   [124 127 137 255]
   [187 191 189 255]]]


 [[[  3   5  19 255]
   [  5   8  25 255]
   [ 12  23  39 255]
   ...
   [ 84  88  97 255]
   [151 153 160 255]
   [ 17  19  33 255]]

  [[  3   5  20 255]
   [  7  10  28 255]
   [

In [ ]:

#print(labels)
labels

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3])

In [ ]:
data[0],data[0].shape

(array([[[ 53,  59,  75, 255],
         [ 29,  35,  51, 255],
         [ 17,  23,  39, 255],
         ...,
         [ 70,  75,  83, 255],
         [ 74,  79,  84, 255],
         [ 79,  84,  88, 255]],
 
        [[ 47,  53,  69, 255],
         [ 48,  54,  70, 255],
         [ 26,  32,  48, 255],
         ...,
         [ 71,  75,  83, 255],
         [ 67,  72,  78, 255],
         [107, 112, 116, 255]],
 
        [[ 35,  41,  57, 255],
         [ 54,  60,  77, 255],
         [ 33,  39,  55, 255],
         ...,
         [ 50,  55,  63, 255],
         [ 83,  88,  94, 255],
         [139, 144, 148, 255]],
 
        ...,
 
        [[  3,   5,  21, 255],
         [  3,   5,  20, 255],
         [  3,   5,  20, 255],
         ...,
         [ 92,  97, 112, 255],
         [141, 144, 153, 255],
         [180, 184, 185, 255]],
 
        [[  3,   5,  20, 255],
         [  3,   5,  20, 255],
         [  3,   5,  20, 255],
         ...,
         [ 64,  69,  86, 255],
         [136, 141, 147, 255],
    

In [ ]:
#image = Image.open(path).convert('L')
#print(image)
mage = Image.open(path + '\'+ a) 
     image = image.resize((30,30)) 
     image = np.array(image) 
     data.append(image) 
     labels.append(i) 
   except: 
        print("Error loading image")

In [ ]:
#Retrieving the images and their labels 
for i in range(classes):
    path = os.path.join(cur_path,'train',str(i))
    images = os.listdir(path)
    #print(images)

    for a in images:
        try:
            image = Image.open(path + '//'+ a)
            image = image.resize((30,30))
            image = np.array(image)
            sim = Image.fromarray(image)
            data.append(image)
            labels.append(i)
        except:
            print("Error loading image")

In [ ]:
#import os
#print(os.listdir('/content/gdrive/MyDrive/Sunik_sample_data/data/train/1'))

In [ ]:
#Converting lists into numpy arrays
data = np.array(data)
labels = np.array(labels)

print(data.shape, labels.shape)